version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "pgdata:/var/lib/postgressql/data"
      - "./database/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - 5432:5432

volumes:
  pgdata:
    driver: local

networks:
  connection_backend_db:
