CREATE TABLE paint (
  manufacturer VARCHAR(255),
  category VARCHAR(255),
  type VARCHAR(255),
  variant_id INTEGER,
  color_name VARCHAR(255),
  color_hex VARCHAR(255),
  image VARCHAR(255)
);

INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70951.0, 'White', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70919.0, 'Cold White', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70842.0, 'Gloss White', '#f1f3f2', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70820.0, 'Offwhite', '#e8eadd', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70918.0, 'Ivory', '#efedd0', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70928.0, 'Light Flesh', '#fcd5c4', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70837.0, 'Pale Sand', '#f8d3b1', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70917.0, 'Beige', '#d9b582', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70916.0, 'Sand Yellow', '#e7b373', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70949.0, 'Light Yellow', '#ffe76e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70952.0, 'Lemon Yellow', '#ffe955', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70806.0, 'German Yellow', '#c0bb7d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70858.0, 'Ice Yellow', '#fbd493', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70915.0, 'Deep Yellow', '#ffe04e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70953.0, 'Flat Yellow', '#ffb14a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70948.0, 'Golden Yellow', '#ffaf5c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70815.0, 'Basic Skin Tone', '#f8b49a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70955.0, 'Flat Flesh', '#e6a07c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70927.0, 'Dark Flesh', '#da9964', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70845.0, 'Sunny Skin Tone', '#f3aa76', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70860.0, 'Medium Flesh Tone', '#b88253', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70911.0, 'Light Orange', '#ff8444', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70805.0, 'German Orange', '#d28078', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70851.0, 'Bright Orange', '#ff6230', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70956.0, 'Clear Orange', '#d94e38', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70817.0, 'Scarlet', '#c74445', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70910.0, 'Orange Red', '#f64a1c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70909.0, 'Vermilion', '#e73120', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70947.0, 'Dark Vermillion', '#bf3c3b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70908.0, 'Carmine Red', '#c32a25', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70957.0, 'Flat Red', '#ac3c3b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70946.0, 'Dark Red', '#874053', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70926.0, 'Red', '#93282b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70814.0, 'Burnt Red', '#5b3c3d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70859.0, 'Black Red', '#473435', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70804.0, 'Beige Red', '#b7836f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70835.0, 'Salmon Rose', '#faa99e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70803.0, 'Brown Rose', '#ae8189', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70944.0, 'Old Rose', '#e27b7c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70958.0, 'Pink', '#c079bb', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70802.0, 'Sunset Red', '#c5426d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70945.0, 'Magenta', '#d22b24', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70812.0, 'Violet Red', '#662440', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70959.0, 'Purple', '#5f5486', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70810.0, 'Royal Purple', '#473e62', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70811.0, 'Blue Violet', '#5a6ab7', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70960.0, 'Violet', '#3b3f71', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70898.0, 'Dark Sea Blue', '#36444c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70807.0, 'Oxford Blue', '#3f4f73', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70899.0, 'Dark Prussian Blue', '#14293a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70965.0, 'Prussian Blue', '#335c7d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70925.0, 'Blue', '#133166', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70930.0, 'Dark Blue', '#2a64a4', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70809.0, 'Royal Blue', '#23609c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70839.0, 'Ultramarine', '#2259ac', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70962.0, 'Flat Blue', '#366ba4', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70963.0, 'Medium Blue', '#24648a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70964.0, 'Field Blue', '#4a6573', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70900.0, 'French Mirage Blue', '#4f6777', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70903.0, 'Intermediate Blue', '#556d7a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70943.0, 'Grey Blue', '#5c86a3', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70902.0, 'Azure', '#578ec3', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70901.0, 'Pastel Blue', '#578a9d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70906.0, 'Pale Blue', '#85aaaa', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70841.0, 'Andrea Blue', '#2aa0cd', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70844.0, 'Deep Sky Blue', '#40bce4', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70961.0, 'Sky Blue', '#67d4f4', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70840.0, 'Light Turquoise', '#289aa8', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70966.0, 'Turquoise', '#2c6e81', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70808.0, 'Blue Green', '#27a9a6', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70838.0, 'Emerald', '#279167', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70970.0, 'Deep Green', '#316552', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70969.0, 'Park Green Flat', '#278163', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70891.0, 'Intermediate Green', '#43964c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70942.0, 'Light Green', '#42a06a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70974.0, 'Green Sky', '#78a183', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70827.0, 'Lime Green', '#81954d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70954.0, 'Yellow Green', '#bed859', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70857.0, 'Golden Olive', '#75814c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70833.0, 'G.C. Bright Green', '#527151', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70850.0, 'Medium Olive', '#327033', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70967.0, 'Olive Green', '#556e4a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70968.0, 'Flat Green', '#405b46', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70922.0, 'Uniform Green', '#4f6a4c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70920.0, 'German Uniform', '#46615e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70823.0, 'Luftwaffe Cam. Green', '#3d4f45', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70892.0, 'Yellow Olive', '#434e47', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70895.0, 'Gunship Green', '#47615a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70975.0, 'Military Green', '#3b443b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70890.0, 'Refractive Green', '#4a5344', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70889.0, 'Olive Brown', '#464947', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70888.0, 'Olive Grey', '#4a5248', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70887.0, 'US Olive Drab', '#545649', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70924.0, 'Russian Unf. WWII', '#5b6050', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70893.0, 'US Dark Green', '#4c544b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70894.0, 'Cam. Olive Green', '#475146', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70979.0, 'G. Cam. Dark Green', '#3f4a47', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70897.0, 'Bronze Green', '#445051', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70896.0, 'G.C. Extra Dark Green', '#3d494a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70980.0, 'Black Green', '#354743', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70886.0, 'Green Grey', '#69736b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70830.0, 'G. Fieldgrey WWII', '#535d57', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70821.0, 'Ger.C. Beige WWII', '#828573', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70884.0, 'Stone Grey', '#939786', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70816.0, 'Luftwaffe Unf. WWII', '#42576a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70971.0, 'Green Grey', '#a5b5ab', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70972.0, 'Light Green Blue', '#66a399', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70973.0, 'Light Sea Grey', '#8eb2b3', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70885.0, 'Pastel Green', '#94a694', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70986.0, 'Deck Tan', '#a3afa7', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70987.0, 'Medium Grey', '#8b8a7e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70881.0, 'Yellow Green', '#6b6b45', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70880.0, 'Khaki Grey', '#7b6a4c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70879.0, 'Green Brown', '#7a6946', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70988.0, 'Khaki', '#78755f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70978.0, 'Dark Yellow', '#888351', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70923.0, 'Japan Uniform WWII', '#987942', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70882.0, 'Middlestone', '#897c53', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70914.0, 'Green Ochre', '#9f835c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70976.0, 'Buff', '#c7ac7f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70913.0, 'Yellow Ochre', '#c28e51', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70912.0, 'Tan Yellow', '#bb956f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70847.0, 'Dark Sand', '#ccad84', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70819.0, 'Iraqi Sand', '#b69c7d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70977.0, 'Desert Yellow', '#b08c65', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70877.0, 'Gold Brown', '#b3814a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70856.0, 'Ochre Brown', '#af7330', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70824.0, 'G.C. Orange Ochre', '#9a7a4f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70929.0, 'Light Brown', '#aa704e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70829.0, 'Amaranth Red', '#c6533d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70981.0, 'Orange Brown', '#be6a3e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70876.0, 'Brown Sand', '#987562', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70843.0, 'Cork Brown', '#a3755b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70874.0, 'Tan Earth', '#85725d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70875.0, 'Beige Brown', '#877563', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70818.0, 'Red Leather', '#895342', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70982.0, 'Cavalry Brown', '#823230', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70940.0, 'Saddle Brown', '#68514e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70846.0, 'Mahogany Brown', '#694f4b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70984.0, 'Flat Brown', '#56423d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70921.0, 'English Uniform', '#685941', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70873.0, 'US Field Drab', '#71624f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70983.0, 'Flat Earth', '#6a5440', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70825.0, 'Ger. Cam. Pale Brown', '#74645a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70826.0, 'Ger. Cam. Med. Brown', '#574d40', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70985.0, 'Hull Red', '#45201d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70871.0, 'Leather Brown', '#504c47', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70941.0, 'Burnt Umber', '#4f4c45', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70872.0, 'Chocolate Brown', '#4b483f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70822.0, 'Ger. C. Black Brown', '#3d4041', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70993.0, 'White Grey', '#e9eeef', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70883.0, 'Silvergrey', '#bec3b9', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70907.0, 'Pale Grey Blue', '#93b3ba', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70989.0, 'Sky Grey', '#93a4ab', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70990.0, 'Light Grey', '#7c93a0', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70905.0, 'Blue Grey Pale', '#6f8b93', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70904.0, 'Dark Blue Grey', '#5c858d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70870.0, 'Medium Sea Grey', '#71848a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70991.0, 'Dark Sea Grey', '#6a7b82', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70992.0, 'Neutral Grey', '#5a707c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70836.0, 'London Grey', '#546976', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70869.0, 'Basalt Grey', '#566972', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70868.0, 'Dark Sea Green', '#465664', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70867.0, 'Dark Blue Grey', '#3e514a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70866.0, 'Grey Green', '#4b5860', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70994.0, 'Dark Grey', '#404f57', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70995.0, 'German Grey', '#38444d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70862.0, 'Black Grey', '#3b474c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70950.0, 'Black', '#21292d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Normal', 70861.0, 'Glossy Black', '#111012', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70997.0, 'Silver', '#c1d4d2', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70996.0, 'Gold', '#ccac5c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70878.0, 'Old Gold', '#93824f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70801.0, 'Brass', '#916b35', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70998.0, 'Bronze', '#6d6a3b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70999.0, 'Copper', '#96563a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70865.0, 'Oily Steel', '#637378', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70864.0, 'Natural Steel', '#798985', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70863.0, 'Gunmetal Grey', '#556663', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic', 70800.0, 'Gunmetal Blue', '#294a5f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Transparent', 70939.0, 'Smoke', '#3b3c37', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Transparent', 70828.0, 'Woodgrain', '#423732', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Transparent', 70834.0, 'Natural Woodgrain', '#f79f42', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Transparent', 70937.0, 'Transparent Yellow', '#ffa12b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Transparent', 70935.0, 'Transparent Orange', '#ffa12b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Transparent', 70934.0, 'Transparent Red', '#c12f38', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Transparent', 70938.0, 'Transparent Blue', '#293b60', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Transparent', 70936.0, 'Transparent Green', '#1c8650', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Glazes', 70853.0, 'White Glaze', '#f1f3f6', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Glazes', 70832.0, 'Verdigris Glaze', '#84d8cc', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Glazes', 70831.0, 'Tan Glaze', '#da8e40', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Glazes', 70854.0, 'Brown Glaze', '#433b3a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Glazes', 70855.0, 'Black Glaze', '#2e3337', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Fluo', 70730.0, 'Yellow Fluo', '#eee662', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Fluo', 70733.0, 'Orange Fluo', '#ff6220', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Fluo', 70735.0, 'Magenta Fluo', '#f951a7', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Fluo', 70736.0, 'Blue Fluo', '#1d76be', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Fluo', 70737.0, 'Green Fluo', '#96d06c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic - Alcohol', 70790.0, 'Silver', '#c9d9dc', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic - Alcohol', 70791.0, 'Gold', '#a89d86', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic - Alcohol', 70792.0, 'Old Gold', '#c1b23d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic - Alcohol', 70793.0, 'Rich Gold', '#a88134', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic - Alcohol', 70794.0, 'Red Gold', '#d08e2d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic - Alcohol', 70795.0, 'Green Gold', '#867231', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic - Alcohol', 70796.0, 'White Gold', '#d6dfe0', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Metallic - Alcohol', 70797.0, 'Copper', '#9f4327', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70540.0, 'Matt Medium', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70470.0, 'Gloss Medium', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70521.0, 'Metal Medium', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70520.0, 'Matt Varnish', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70510.0, 'Gloss Varnish', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70522.0, 'Satin Varnish', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70596.0, 'Glaze Medium', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70597.0, 'Retarder Medium', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70523.0, 'Liquid Mask', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70598.0, 'Crackle Medium', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70400.0, 'Plastic Putty', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 70524.0, 'Thinner', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 71261.0, 'Airbrush Thinner', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 71262.0, 'Flow Improver', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 73212.0, 'Decal Softener', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 73213.0, 'Decal Fix', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Model Color', 'Mediums & Auxiliary', 73214.0, 'Chipping Medium', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72001.0, 'Dead White', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72002.0, 'White Primer', '#ffffff', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72003.0, 'Pale Flesh', '#f0b9a5', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72004.0, 'Elf Skintone', '#e49d75', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72005.0, 'Moon Yellow', '#ffdd3b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72006.0, 'Sun Yellow', '#ff9929', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72007.0, 'Gold Yellow', '#ff8e29', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72008.0, 'Orange Fire', '#ff6626', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72009.0, 'Hot Orange', '#ff522d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72010.0, 'Bloody Red', '#cf2a35', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72011.0, 'Gory Red', '#6f373c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72012.0, 'Scarlet Red', '#a2202f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72013.0, 'Squid Pink', '#ce87c2', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72014.0, 'Warlord Purple', '#b23684', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72015.0, 'Hexed Lichen', '#3a2f91', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72016.0, 'Royal Purple', '#394166', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72017.0, 'Dark Blue', '#364880', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72018.0, 'Stormy Blue', '#343e5c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72019.0, 'Night Blue', '#303646', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72020.0, 'Imperial Blue', '#2b4867', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72021.0, 'Magic Blue', '#1a74bf', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72022.0, 'Ultramarine Blue', '#1e5896', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72023.0, 'Electric Blue', '#369dbd', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72024.0, 'Turquoise', '#198b97', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72025.0, 'Foul Green', '#3eab8b', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72026.0, 'Jade Green', '#039375', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72027.0, 'Scurvy Green', '#285753', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72028.0, 'Dark Green', '#2e413c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72029.0, 'Sick Green', '#437055', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72030.0, 'Goblin Green', '#5e7147', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72031.0, 'Camouflage Green', '#827943', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72032.0, 'Scorpy Green', '#67b15c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72033.0, 'Livery Green', '#8ccd68', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72034.0, 'Bonewhite', '#cdbb95', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72035.0, 'Dead Flesh', '#a99f71', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72036.0, 'Bronze Fleshtone', '#c8814c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72037.0, 'Filthy Brown', '#c77d3f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72038.0, 'Scrofulous Brown', '#be7437', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72039.0, 'Plague Brown', '#d88b2c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72040.0, 'Leather Brown', '#7d5f3e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72041.0, 'Dwarf Skin', '#de8c6a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72042.0, 'Parasite Brown', '#a54f1f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72043.0, 'Beasty Brown', '#6e523f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72044.0, 'Dark Fleshtone', '#563b38', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72045.0, 'Charred Brown', '#413b3a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72046.0, 'Ghost Grey', '#b0cad3', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72047.0, 'Wolf Grey', '#9ec0ce', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72048.0, 'Sombre Grey', '#4f6b84', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72049.0, 'Stonewall Grey', '#8f9ea2', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72050.0, 'Cold Grey', '#6d7b81', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72051.0, 'Black', '#030104', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72052.0, 'Silver', '#94aab0', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72053.0, 'Chainmail Silver', '#6d7b81', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72054.0, 'Gunmetal', '#556269', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72055.0, 'Polished Gold', '#f9a72e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72056.0, 'Glorious Gold', '#966a38', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72057.0, 'Bright Bronze', '#8e634e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72058.0, 'Brassy Brass', '#7e5039', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72059.0, 'Hammered Copper', '#724235', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72060.0, 'Tinny Tin', '#44292a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72061.0, 'Khaki', '#9e9b74', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72062.0, 'Earth', '#705e47', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72063.0, 'Desert Yellow', '#90854c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72064.0, 'Yellow Olive', '#47532d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72065.0, 'Terracotta', '#603938', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72066.0, 'Tan', '#a9574f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72067.0, 'Cayman Green', '#515745', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72068.0, 'Smokey Ink', '#262123', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72095.0, 'Glacier Blue', '#9fcdeb', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72096.0, 'Verdigris', '#91dcd3', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72097.0, 'Pale Yellow', '#eccb80', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72098.0, 'Elfic Flesh', '#e8d3b4', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72099.0, 'Cadmium Skin', '#ffaa82', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72100.0, 'Rosy Flesh', '#fa9189', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72101.0, 'Off White', '#fff0d7', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72102.0, 'Steel Grey', '#396981', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72103.0, 'Fluo Yellow', '#dade50', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72104.0, 'Fluo Green', '#60c156', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72105.0, 'Mutation Green', '#395745', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Normal', 72106.0, 'Scarlet Red', '#b03a38', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72085.0, 'Yellow', '#ffa52d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72086.0, 'Red', '#d83c72', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72087.0, 'Violet', '#51329a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72088.0, 'Blue', '#0550aa', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72089.0, 'Green', '#3fbd7a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72090.0, 'Black Green', '#2b3b34', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72091.0, 'Sepia', '#a39da6', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72092.0, 'Brown', '#86401e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72093.0, 'Skin Wash', '#af3f1e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Game Color Inks', 72094.0, 'Black', '#22211f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72140.0, 'Heavy Skintone', '#987562', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72141.0, 'Heavy Red', '#8b333d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72142.0, 'Heavy Violet', '#3b3f71', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72143.0, 'Heavy Blue', '#335c7d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72144.0, 'Heavy Bluegrey', '#6f8b93', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72145.0, 'Heavy Grey', '#5b6050', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72146.0, 'Heavy Green', '#3d4f45', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72147.0, 'Heavy Blackgreen', '#354743', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72148.0, 'Heavy Warmgrey', '#9e9b74', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72149.0, 'Heavy Khaki', '#897c53', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72150.0, 'Heavy Ochre', '#af7330', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72151.0, 'Heavy Goldbrown', '#b3814a', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72152.0, 'Heavy Orange', '#d28078', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72153.0, 'Heavy Brown', '#71624f', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72154.0, 'Heavy Sienna', '#56423d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Extra Opaque Colors', 72155.0, 'Heavy Charcoal', '#38444d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Washes', 73200.0, 'Sepia Wash', '#855c2e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Washes', 73201.0, 'Black Wash', '#262930', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Washes', 73202.0, 'Pale Grey Wash', '#b9cacd', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Washes', 73203.0, 'Umber Wash', '#645a50', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Washes', 73204.0, 'Flesh Wash', '#b17974', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Washes', 73205.0, 'Green Wash', '#66bc69', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Washes', 73206.0, 'Red Wash', '#dd608c', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Washes', 73207.0, 'Blue Wash', '#165fa2', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Special Effect Colors', 72130.0, 'Rotten White', '#dce8e4', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Special Effect Colors', 72131.0, 'Rust', '#ff581e', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Special Effect Colors', 72132.0, 'Fresh Blood', '#7e2916', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Special Effect Colors', 72133.0, 'Dried Blood', '#5b2419', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Special Effect Colors', 72134.0, 'Vomit', '#7a7b3d', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Special Effect Colors', 72135.0, 'Verdigris', '#49a492', '""');
INSERT INTO paint (manufacturer, category, type, variant_id, color_name, color_hex, image) VALUES ('Vallejo', 'Game Color', 'Special Effect Colors', 72136.0, 'Dry Rust', '#443b31', '""');
